[package]
name = "icrc45"
version = "1.0.0"
description = "Icrc45 Market Data"
repository = ""
keywords = [ "defi", "market", "data" ]
license = "Apache-2.0"

[dependencies]
base = "0.11.3"
vector = "0.3.1"
